mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.springmvc2.pojo
server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springtest?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      max-active: 50
      initial-size: 5
  mvc:
    static-path-pattern: /static/**

    locale: #指定国际化区域
    locale-resolver: accept_header #国际化解析器，accept_header代表读取浏览器头消息

  servlet:
    multipart:
      enabled: true #是否开启SpringMVC多分布上传功能
      file-size-threshold: 0 #将文件写入磁盘阈值，值可以使用后缀“MB”或者是“KB”来表示兆字节大小
      location: E:\Downloads #指定默认上传文件夹地址
      max-file-size: 5MB #设置单个文件最大值
      max-request-size: 100MB #设置所有文件最大值
      resolve-lazily: false #是否延迟多部件文件请求的参数和文件解析

  messages:
    encoding: utf-8 #文件编码
    basename: international #国家化文件基础
    cache-duration: 3600 #国际化消息缓存有效时间（单位秒），超时重载
