server:
  port: 8888

mybatis:
  mapper-locations: classpath:/mapperxml/*Mapper.xml


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.78.128:3306/springtest?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

  elasticsearch:
    jest:
      uris:
        - http://192.168.78.128:9200  # ES服务器的地址！
      read-timeout: 5000
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.78.128:9300

